### PR TITLE
Fix varint7 bug

### LINKED ISSUE #184: Fuzzer: integer repr too long / invalid type -388
```
AGFzbQEAAAABDQFgCHx8/Hx8fHx8AXwDAwIAAAcyAhNkb3RfcHJvZHVjdF9leGFtcGxlAAAYd2l0aF9iaW5hcnlfc3VtX2NvbGxhcHNlAAEKNQIZACAAIASiIAEgBaKgIAIgBqKgIAMgB6KgCxkAIAAgBKIgASAFoqAgAiAGoiADIAeioKAL
```

wasm: ```test.wasm:0x10: decoding error: integer representation too long```
wabt: ```0000011: error: invalid type: -388```

parity-wasm reports OK

### LINKED ISSUE #185: Fuzzer: invalid type of table
```
AGFzbQEAAAAEBQHwAQABBwUBAWEBAA==
```

wabt:

```
BeginModule(version: 1)
  BeginTableSection(5)
    OnTableCount(1)
000000d: error: invalid type: 240
```

spec:

```
test.wasm:0xc: decoding error: integer representation too long
```

### PR DESCRIPTION
**Pull request by NikVolf**
Fixes #184
Fixes #185

### CODE REVIEW

File: src/elements/primitives.rs [hunk 1]
```diff
@@ -793,6 +799,25 @@ mod tests {
 		);
 	}
 
+	#[test]
+	#[should_panic]
+	fn varint7_invalid() {
+		deserialize_buffer::<VarInt7>(&[240]).expect("fail");
```
Comment (pepyakin) [inline src/elements/primitives.rs]: What do you think about changing `#[should_panic]` + `expect` to the explicit check
like

```rust
match deserialize_buffer::<VarInt7>(&[240]) {
    Err(Error::InvalidVarInt7(_)) => {},
    _ => panic!()
}
```
